python3.7 image_downloads.py apidata/instances_train2017.json person
python3.7 image_downloads.py apidata/instances_train2017.json bus
python3.7 image_downloads.py apidata/instances_train2017.json airplane
python3.7 image_downloads.py apidata/instances_train2017.json train
python3.7 image_downloads.py apidata/instances_train2017.json car
python3.7 image_downloads.py apidata/instances_train2017.json dog
python3.7 image_downloads.py apidata/instances_train2017.json not
python3.7 image_downloads.py apidata/instances_train2017.json person
python3.7 image_downloads.py apidata/instances_val2017.json bus
python3.7 image_downloads.py apidata/instances_val2017.json airplane
python3.7 image_downloads.py apidata/instances_val2017.json train
python3.7 image_downloads.py apidata/instances_val2017.json car
python3.7 image_downloads.py apidata/instances_val2017.json dog
python3.7 image_downloads.py apidata/instances_val2017.json not